Rails.application.routes.draw do

  root to: "paneur#map"

  # get 'paneur/overview'
  # get 'paneur/archival_sources'

  # Map
  get 'paneur/map'
  
  # Generated by the resource 'countries'
  #get '/countries/:id', to: 'countries#show'

  # get 'items/show'
  # get 'items/view_all'
  # get 'items/new'
  # get 'items/destroy'

  # Default routes are used so far.
  resources :countries, controller: 'countries'
  resources :elites, controller: 'elites'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
