Country.create!([
  {Id: 2, Description: "Country description here...", FlagId: nil, Name: "Hungary"},
  {Id: 1, Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", FlagId: nil, Name: "Italy"}
])
DBFile.create!([
  {Id: 10, ArchivalCode: "MNL OL XIX-A-90-c box 168", Date: 1015073, Description: "<p>ABC</p>", FileName: nil, LanguageBlob: "Hungarian", Name: "(Institute of Economics of the Hungarian Academy of Sciences?): Relations between the COMECON and the EEC 1963-1977", ReferenceNumber: "00912/NKGT/77, K/0059/78", TypeId: 1},
  {Id: 9, ArchivalCode: "MNL OL XIX-A-39 box 250", Date: 1015073, Description: "<p>ABC</p>", FileName: "DOC 0001 DSC06246.pdf", LanguageBlob: "Hungarian", Name: "No. 10129/1982. decree of the Economic Council: About our economic and commercial policy towards the Common Market (European Economic Community), the possibilities for developing these policies ", ReferenceNumber: "10.129/1982", TypeId: 1}
])
Elite.create!([
  {Id: 8, CountryId: 1, Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac congue nunc. Nam pulvinar mi ac sem commodo, eu ullamcorper magna facilisis. Nunc eu justo tortor. Nullam dolor massa, ultrices quis tristique sit amet, luctus quis metus. Praesent eget cursus tellus, nec ultricies neque. Pellentesque pulvinar blandit eros id mollis. Morbi dignissim tortor tristique turpis sollicitudin porttitor. Vestibulum eu ultrices mauris. Nam eget justo eget leo pulvinar luctus. Fusce euismod, orci in hendrerit rhoncus, purus augue convallis ipsum, eget vestibulum nisl purus congue dui. Aenean cursus venenatis magna imperdiet efficitur. Vestibulum eget velit quis velit sodales hendrerit. Vestibulum bibendum nisi sit amet sodales porttitor. Vestibulum eu vestibulum nunc, vitae lacinia augue. Proin gravida sem nec scelerisque finibus. Pellentesque blandit libero sit amet ornare posuere.", Name: "Elite Group", TypeId: 3},
  {Id: 10, CountryId: 1, Description: nil, Name: "Elite Group", TypeId: 5},
  {Id: 9, CountryId: 1, Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac congue nunc. Nam pulvinar mi ac sem commodo, eu ullamcorper magna facilisis. Nunc eu justo tortor. Nullam dolor massa, ultrices quis tristique sit amet, luctus quis metus. Praesent eget cursus tellus, nec ultricies neque. Pellentesque pulvinar blandit eros id mollis. Morbi dignissim tortor tristique turpis sollicitudin porttitor. Vestibulum eu ultrices mauris. Nam eget justo eget leo pulvinar luctus. Fusce euismod, orci in hendrerit rhoncus, purus augue convallis ipsum, eget vestibulum nisl purus congue dui. Aenean cursus venenatis magna imperdiet efficitur. Vestibulum eget velit quis velit sodales hendrerit. Vestibulum bibendum nisi sit amet sodales porttitor. Vestibulum eu vestibulum nunc, vitae lacinia augue. Proin gravida sem nec scelerisque finibus. Pellentesque blandit libero sit amet ornare posuere.", Name: "Elite Group", TypeId: 4},
  {Id: 6, CountryId: 1, Description: "Donec convallis lectus convallis lectus sodales malesuada quis eu leo. Vestibulum sed diam id magna rhoncus elementum mollis tristique turpis. Praesent quis elementum lectus, non egestas nunc. Duis eu felis elementum, pulvinar odio ut, commodo urna. Suspendisse ut euismod tellus. Donec interdum tristique ex vel porta. Maecenas pretium ex ut elementum congue. Suspendisse malesuada enim eu ante mattis, eget consectetur velit finibus. Sed tempor velit et arcu pretium, sit amet eleifend urna vehicula. Nunc iaculis facilisis vulputate. Suspendisse purus nulla, lobortis sit amet nibh sed, feugiat sodales neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris gravida feugiat sapien, vitae fermentum nibh elementum fermentum.", Name: "Elite Group", TypeId: 1},
  {Id: 7, CountryId: 1, Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac congue nunc. Nam pulvinar mi ac sem commodo, eu ullamcorper magna facilisis. Nunc eu justo tortor. Nullam dolor massa, ultrices quis tristique sit amet, luctus quis metus. Praesent eget cursus tellus, nec ultricies neque. Pellentesque pulvinar blandit eros id mollis. Morbi dignissim tortor tristique turpis sollicitudin porttitor. Vestibulum eu ultrices mauris. Nam eget justo eget leo pulvinar luctus. Fusce euismod, orci in hendrerit rhoncus, purus augue convallis ipsum, eget vestibulum nisl purus congue dui. Aenean cursus venenatis magna imperdiet efficitur. Vestibulum eget velit quis velit sodales hendrerit. Vestibulum bibendum nisi sit amet sodales porttitor. Vestibulum eu vestibulum nunc, vitae lacinia augue. Proin gravida sem nec scelerisque finibus. Pellentesque blandit libero sit amet ornare posuere.", Name: "Elite Group", TypeId: 2}
])
EliteType.create!([
  {Id: 2, Name: "Trade Organisations"},
  {Id: 3, Name: "Central Bank"},
  {Id: 4, Name: "Goverment"},
  {Id: 5, Name: "Party"},
  {Id: 1, Name: "Academia"}
])
FileType.create!([
  {Id: 1, Name: "Document"},
  {Id: 2, Name: "Person Photo"},
  {Id: 3, Name: "Country Flag"}
])
Language.create!([
  {Id: 1, Name: "Slovenian"},
  {Id: 2, Name: "Estonian"},
  {Id: 3, Name: "Latvian"},
  {Id: 4, Name: "Russian"},
  {Id: 5, Name: "Lithuanian"},
  {Id: 6, Name: "Swedish"},
  {Id: 7, Name: "Italian"},
  {Id: 8, Name: "Spanish"},
  {Id: 9, Name: "English"},
  {Id: 10, Name: "Finnish"},
  {Id: 11, Name: "Irish"},
  {Id: 12, Name: "Slovak"},
  {Id: 13, Name: "Bulgarian"},
  {Id: 14, Name: "French"},
  {Id: 15, Name: "Maltese"},
  {Id: 16, Name: "Croatian"},
  {Id: 17, Name: "Polish"},
  {Id: 18, Name: "Czech"},
  {Id: 19, Name: "German"},
  {Id: 20, Name: "Portuguese"},
  {Id: 21, Name: "Danish"},
  {Id: 22, Name: "Hungarian"},
  {Id: 23, Name: "Romanian"},
  {Id: 24, Name: "Dutch"},
  {Id: 25, Name: "Greek"}
])
Nationality.create!([
  {Id: 1, Country: "Montenegro", NationalityAdjective: "Montenegrin"},
  {Id: 2, Country: "Nicaragua", NationalityAdjective: "Nicaraguan"},
  {Id: 3, Country: "Morocco", NationalityAdjective: "Moroccan"},
  {Id: 4, Country: "Mozambique", NationalityAdjective: "Mozambican"},
  {Id: 5, Country: "Namibia", NationalityAdjective: "Namibian"},
  {Id: 6, Country: "Nepal", NationalityAdjective: "Nepalese"},
  {Id: 7, Country: "Niger", NationalityAdjective: "Nigerien"},
  {Id: 8, Country: "Poland", NationalityAdjective: "Pole"},
  {Id: 9, Country: "Norway", NationalityAdjective: "Norwegian"},
  {Id: 10, Country: "Pakistan", NationalityAdjective: "Pakistani"},
  {Id: 11, Country: "Panama", NationalityAdjective: "Panamanian"},
  {Id: 12, Country: "Paraguay", NationalityAdjective: "Paraguayan"},
  {Id: 13, Country: "Peru", NationalityAdjective: "Peruvian"},
  {Id: 14, Country: "Philippines", NationalityAdjective: "Filipino"},
  {Id: 15, Country: "Mongolia", NationalityAdjective: "Mongolian"},
  {Id: 16, Country: "Nigeria", NationalityAdjective: "Nigerian"},
  {Id: 17, Country: "Monaco", NationalityAdjective: "Monacan"},
  {Id: 18, Country: "Lebanon", NationalityAdjective: "Lebanese"},
  {Id: 19, Country: "Mexico", NationalityAdjective: "Mexican"},
  {Id: 20, Country: "Latvia", NationalityAdjective: "Latvian"},
  {Id: 21, Country: "Portugal", NationalityAdjective: "Portuguese"},
  {Id: 22, Country: "Liberia", NationalityAdjective: "Liberian"},
  {Id: 23, Country: "Libya", NationalityAdjective: "Libyan"},
  {Id: 24, Country: "Liechtenstein", NationalityAdjective: "Liechtensteiner"},
  {Id: 25, Country: "Lithuania", NationalityAdjective: "Lithuanian"},
  {Id: 26, Country: "Luxembourg", NationalityAdjective: "Luxembourger"},
  {Id: 27, Country: "Moldova", NationalityAdjective: "Moldovan"},
  {Id: 28, Country: "Macedonia", NationalityAdjective: "Macedonian"},
  {Id: 29, Country: "Malawi", NationalityAdjective: "Malawian"},
  {Id: 30, Country: "Malaysia", NationalityAdjective: "Malaysian"},
  {Id: 31, Country: "Maldives", NationalityAdjective: "Maldivian"},
  {Id: 32, Country: "Mali", NationalityAdjective: "Malian"},
  {Id: 33, Country: "Malta", NationalityAdjective: "Maltese"},
  {Id: 34, Country: "Mauritania", NationalityAdjective: "Mauritanian"},
  {Id: 35, Country: "Mauritius", NationalityAdjective: "Mauritian"},
  {Id: 36, Country: "Madagascar", NationalityAdjective: "Madagascan"},
  {Id: 37, Country: "Qatar", NationalityAdjective: "Qatari"},
  {Id: 38, Country: "Sweden", NationalityAdjective: "Swede"},
  {Id: 39, Country: "Russia", NationalityAdjective: "Russian"},
  {Id: 40, Country: "Thailand", NationalityAdjective: "Thai"},
  {Id: 41, Country: "Togo", NationalityAdjective: "Togolese"},
  {Id: 42, Country: "Trinidad", NationalityAdjective: "Trinidadian"},
  {Id: 43, Country: "Tunisia", NationalityAdjective: "Tunisian"},
  {Id: 44, Country: "Turkey", NationalityAdjective: "Turk"},
  {Id: 45, Country: "Uganda", NationalityAdjective: "Ugandan"},
  {Id: 46, Country: "Ukraine", NationalityAdjective: "Ukrainian"},
  {Id: 47, Country: "Tanzania", NationalityAdjective: "Tanzanian"},
  {Id: 48, Country: "United Kingdom", NationalityAdjective: "British"},
  {Id: 49, Country: "Uruguay", NationalityAdjective: "Uruguayan"},
  {Id: 50, Country: "Uzbekistan", NationalityAdjective: "Uzbek"},
  {Id: 51, Country: "Venezuela", NationalityAdjective: "Venezuelan"},
  {Id: 52, Country: "Vietnam", NationalityAdjective: "Vietnamese"},
  {Id: 53, Country: "Wales", NationalityAdjective: "Welshman"},
  {Id: 54, Country: "Yemen", NationalityAdjective: "Yemeni"},
  {Id: 55, Country: "Yugoslavia", NationalityAdjective: "Yugoslav"},
  {Id: 56, Country: "United States", NationalityAdjective: "American"},
  {Id: 57, Country: "Romania", NationalityAdjective: "Romanian"},
  {Id: 58, Country: "Tajikistan", NationalityAdjective: "Tadzhik"},
  {Id: 59, Country: "Syria", NationalityAdjective: "Syrian"},
  {Id: 60, Country: "Rwanda", NationalityAdjective: "Rwandan"},
  {Id: 61, Country: "Saudi Arabia", NationalityAdjective: "Saudi"},
  {Id: 62, Country: "Scotland", NationalityAdjective: "Scot"},
  {Id: 63, Country: "Senegal", NationalityAdjective: "Senegalese"},
  {Id: 64, Country: "Serbia", NationalityAdjective: "Serbian"},
  {Id: 65, Country: "Singapore", NationalityAdjective: "Singaporean"},
  {Id: 66, Country: "Slovakia", NationalityAdjective: "Slovak"},
  {Id: 67, Country: "Taiwan", NationalityAdjective: "Taiwanese"},
  {Id: 68, Country: "Slovenia", NationalityAdjective: "Slovenian"},
  {Id: 69, Country: "Spain", NationalityAdjective: "Spaniard"},
  {Id: 70, Country: "Sri Lanka", NationalityAdjective: "Sri Lankan"},
  {Id: 71, Country: "Sudan", NationalityAdjective: "Sudanese"},
  {Id: 72, Country: "Suriname", NationalityAdjective: "Surinamese"},
  {Id: 73, Country: "Swaziland", NationalityAdjective: "Swazi"},
  {Id: 74, Country: "Laos", NationalityAdjective: "Laotian"},
  {Id: 75, Country: "Switzerland", NationalityAdjective: "Swiss"},
  {Id: 76, Country: "Somalia", NationalityAdjective: "Somali"},
  {Id: 77, Country: "Kuwait", NationalityAdjective: "Kuwaiti"},
  {Id: 78, Country: "Honduras", NationalityAdjective: "Honduran"},
  {Id: 79, Country: "Kenya", NationalityAdjective: "Kenyan"},
  {Id: 80, Country: "Britain", NationalityAdjective: "Briton"},
  {Id: 81, Country: "Brunei", NationalityAdjective: "Bruneian"},
  {Id: 82, Country: "Bulgaria", NationalityAdjective: "Bulgarian"},
  {Id: 83, Country: "Burma", NationalityAdjective: "Burmese"},
  {Id: 84, Country: "Burundi", NationalityAdjective: "Burundian"},
  {Id: 85, Country: "Cambodia", NationalityAdjective: "Cambodian"},
  {Id: 86, Country: "Cameroon", NationalityAdjective: "Cameroonian"},
  {Id: 87, Country: "Canada", NationalityAdjective: "Canadian"},
  {Id: 88, Country: "Chad", NationalityAdjective: "Chadian"},
  {Id: 89, Country: "Chile", NationalityAdjective: "Chilean"},
  {Id: 90, Country: "China", NationalityAdjective: "Chinese"},
  {Id: 91, Country: "Colombia", NationalityAdjective: "Colombian"},
  {Id: 92, Country: "Congo", NationalityAdjective: "Congolese"},
  {Id: 93, Country: "Croatia", NationalityAdjective: "Croatian"},
  {Id: 94, Country: "Cuba", NationalityAdjective: "Cuban"},
  {Id: 95, Country: "Brazil", NationalityAdjective: "Brazilian"},
  {Id: 96, Country: "Bosnia-Herzegovina", NationalityAdjective: "Bosnian"},
  {Id: 97, Country: "Bolivia", NationalityAdjective: "Bolivian"},
  {Id: 98, Country: "Bhutan", NationalityAdjective: "Bhutanese"},
  {Id: 99, Country: "Afghanistan", NationalityAdjective: "Afghan"},
  {Id: 100, Country: "Albania", NationalityAdjective: "Albanian"},
  {Id: 101, Country: "Algeria", NationalityAdjective: "Algerian"},
  {Id: 102, Country: "Andorra", NationalityAdjective: "Andorran"},
  {Id: 103, Country: "Angola", NationalityAdjective: "Angolan"},
  {Id: 104, Country: "Argentina", NationalityAdjective: "Argentinian"},
  {Id: 105, Country: "Armenia", NationalityAdjective: "Armenian"},
  {Id: 106, Country: "Cyprus", NationalityAdjective: "Cypriot"},
  {Id: 107, Country: "Australia", NationalityAdjective: "Australian"},
  {Id: 108, Country: "Azerbaijan", NationalityAdjective: "Azerbaijani"},
  {Id: 109, Country: "Bahamas", NationalityAdjective: "Bahamian"},
  {Id: 110, Country: "Bangladesh", NationalityAdjective: "Bangladeshi"},
  {Id: 111, Country: "Barbados", NationalityAdjective: "Barbadian"},
  {Id: 112, Country: "Belarus", NationalityAdjective: "Belorussian"},
  {Id: 113, Country: "Belgium", NationalityAdjective: "Belgian"},
  {Id: 114, Country: "Benin", NationalityAdjective: "Beninese"},
  {Id: 115, Country: "Austria", NationalityAdjective: "Austrian"},
  {Id: 116, Country: "Czech Republic", NationalityAdjective: "Czech"},
  {Id: 117, Country: "Denmark", NationalityAdjective: "Dane"},
  {Id: 118, Country: "Dominica", NationalityAdjective: "Dominican"},
  {Id: 119, Country: "Haiti", NationalityAdjective: "Haitian"},
  {Id: 120, Country: "Holland", NationalityAdjective: "Dutchman"},
  {Id: 121, Country: "Zambia", NationalityAdjective: "Zambian"},
  {Id: 122, Country: "Hungary", NationalityAdjective: "Hungarian"},
  {Id: 123, Country: "Iceland", NationalityAdjective: "Icelander"},
  {Id: 124, Country: "India", NationalityAdjective: "Indian"},
  {Id: 125, Country: "Indonesia", NationalityAdjective: "Indonesian"},
  {Id: 126, Country: "Guyana", NationalityAdjective: "Guyanese"},
  {Id: 127, Country: "Iran", NationalityAdjective: "Iranian"},
  {Id: 128, Country: "Ireland", NationalityAdjective: "Irishman"},
  {Id: 129, Country: "Israel", NationalityAdjective: "Israeli"},
  {Id: 130, Country: "Italy", NationalityAdjective: "Italian"},
  {Id: 131, Country: "Jamaica", NationalityAdjective: "Jamaican"},
  {Id: 132, Country: "Japan", NationalityAdjective: "Japanese"},
  {Id: 133, Country: "Jordan", NationalityAdjective: "Jordanian"},
  {Id: 134, Country: "Kazakhstan", NationalityAdjective: "Kazakh"},
  {Id: 135, Country: "Iraq", NationalityAdjective: "Iraqi"},
  {Id: 136, Country: "Korea", NationalityAdjective: "Korean"},
  {Id: 137, Country: "Guinea", NationalityAdjective: "Guinean"},
  {Id: 138, Country: "Grenada", NationalityAdjective: "Grenadian"},
  {Id: 139, Country: "Ecuador", NationalityAdjective: "Ecuadorean"},
  {Id: 140, Country: "Egypt", NationalityAdjective: "Egyptian"},
  {Id: 141, Country: "El Salvador", NationalityAdjective: "Salvadorean"},
  {Id: 142, Country: "England", NationalityAdjective: "Englishman"},
  {Id: 143, Country: "Eritrea", NationalityAdjective: "Eritrean"},
  {Id: 144, Country: "Estonia", NationalityAdjective: "Estonian"},
  {Id: 145, Country: "Ethiopia", NationalityAdjective: "Ethiopian"},
  {Id: 146, Country: "Guatemala", NationalityAdjective: "Guatemalan"},
  {Id: 147, Country: "Fiji", NationalityAdjective: "Fijian"},
  {Id: 148, Country: "France", NationalityAdjective: "Frenchman"},
  {Id: 149, Country: "Gabon", NationalityAdjective: "Gabonese"},
  {Id: 150, Country: "Gambia", NationalityAdjective: "Gambian"},
  {Id: 151, Country: "Georgia", NationalityAdjective: "Georgian"},
  {Id: 152, Country: "Germany", NationalityAdjective: "German"},
  {Id: 153, Country: "Ghana", NationalityAdjective: "Ghanaian"},
  {Id: 154, Country: "Greece", NationalityAdjective: "Greek"},
  {Id: 155, Country: "Finland", NationalityAdjective: "Finn"},
  {Id: 156, Country: "Zimbabwe", NationalityAdjective: "Zimbabwean"}
])
PeopleElite.create!([
  {Id: 8, DateOfEmployment: 0, DateOfResignation: 0, EliteId: 6, MapVisible: true, PersonId: 129, Position: "Test Position"}
])
Person.create!([
  {Id: 114, DateOfBirth: 979528, DateOfDeath: 1021321, Description: "<p>As one of the older generation orthodox communists, he never questioned the Soviet viewpoint on the Western integration. However, during the CMEA talks he strongly propagated the Hungarian stance to deepen the Eastern integration and the closest cooperation between the partner states.</p>", DocumentsBlob: "", ElitesBlob: "Vice president of the Executive Council, 1957-1971; Permanent representative of Hungary in the CMEA 1961-1971", Name: "Antal", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Szeged", PlaceOfDeath: "Budapest", RelationsBlob: "N. Faddeev, secretary general of the CMEA", Surname: "Apró"},
  {Id: 115, DateOfBirth: 983629, DateOfDeath: 1024690, Description: "<p></p>", DocumentsBlob: "", ElitesBlob: "deputy minister of foreign trade 1962-1963; minister of foreign trade 1963-1979", Name: "József", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Budapest", PlaceOfDeath: "Budapest", RelationsBlob: "", Surname: "Bíró"},
  {Id: 116, DateOfBirth: 981573, DateOfDeath: 1022307, Description: "<p>His research field covered the economic challenges of the socialist and developing countries and the Eastern-Western economic relations. He was one of the elaborators of the New Economic Mechanism, promoter of the “socialist market economy” theory and the Western opening. The founder director of the Institute for Research on World Economy</p>", DocumentsBlob: "", ElitesBlob: "minister of internal trade 1949-1956 (in 1953-54 he leaded the joint ministry of internal and foreign trade); professor at the Karl Marx University of Economics since 1954; the dean of the commercial faculty of the university 1957-1961; headed the Research Centre for Afro-Asian Studies of the HAS 1963-1973; director of the Research on World Economy of the HAS 1973-1987 ", Name: "József", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Szombathely", PlaceOfDeath: "Budapest", RelationsBlob: "", Surname: "Bognár"},
  {Id: 117, DateOfBirth: 981169, DateOfDeath: 1024694, Description: "<p>He had a crucial role in the launching the economic reform from the mid-sixties. As a Prime Minister he urged and supported the deeper cooperation of the CMEA countries and the economic opening towards the West</p>", DocumentsBlob: "", ElitesBlob: "economic policy secretary of the HSWP CC 1957-1961; vice-president of the Executive Council 1961-1967; Prime Minister 1967-1975", Name: "Jenő", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Kispest", PlaceOfDeath: "Budapest", RelationsBlob: "", Surname: "Fock"},
  {Id: 118, DateOfBirth: 987732, DateOfDeath: 1020611, Description: "<p>As the supervisor of the economic policy was involved in the negotiations with the EEC</p>", DocumentsBlob: "", ElitesBlob: "first secretary of the HSWP Komárom County Committee 1966-1975; first vice-president of the Executive Council 1975-1978; the economic policy secretary of the HSWP CC 1978-1987", Name: "Ferenc", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Piszke", PlaceOfDeath: "Tata", RelationsBlob: "", Surname: "Havasi"},
  {Id: 119, DateOfBirth: 989413, DateOfDeath: 1030899, Description: "<p>In 1987-88 he was the member of the Committee for International Economic Relations, when the agreement between Hungary and the EEC was concluded and signed</p>", DocumentsBlob: "", ElitesBlob: "Deputy leader of the HSWP CC's Foreign Affairs Department, 1974-1983; head of the HSWP CC's Foreign Affairs Department 1983-1985; undersecretary of the Ministry of Foreign Affairs 1985-1989; minister of foreign affairs 1989-1990", Name: "Gyula", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Budapest", PlaceOfDeath: "Budapest", RelationsBlob: "", Surname: "Horn"},
  {Id: 120, DateOfBirth: 988672, DateOfDeath: 1026560, Description: "<p>Leading researcher of the economic integrations, one of his most important books: Economic integration and economic strategy. Budapest, Akadémiai Kiadó, 1982.</p>", DocumentsBlob: "https://books.google.it/books?id=OUjrCAAAQBAJ&pg=PA4&lpg=PA4&dq=kozma+ferenc+economic+integration+and+economic+strategy&source=bl&ots=twoPqtbCWk&sig=wPw8X96UXgT_ZPyrUIaTnyReBvo&hl=hu&sa=X&ved=0ahUKEwjO462QyuLTAhXCKlAKHdEdBrIQ6AEINzAC#v=onepage&q=kozma%20ferenc%20economic%20integration%20and%20economic%20strategy&f=false", ElitesBlob: "researcher at the HAS Institute of Economics 1962-1968; senior researcher at the Research Institute on Socialist World Economy of the Soviet Union Academy of Sciences in Moscow 1967-1968; department leader at the Secretary of the Committee for International Economic Relations 1968-1984; deputy rector of the HSWP Political College 1984-1989; professor of the Karl Marx University of Economics 1978-1989", Name: "Ferenc", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Szolnok", PlaceOfDeath: "", RelationsBlob: "", Surname: "Kozma"},
  {Id: 121, DateOfBirth: 995461, DateOfDeath: 0, Description: "<p>As a commercial secretary in Brussles he participated the debates of the Socialist embassies, later in Budapest, at the Ministry of Foreign Trade he was the member of the coordination board dealing with the EEC agricultural embargo after the Chernobyl disaster</p>", DocumentsBlob: "", ElitesBlob: "commercial secretary at the Hungarian Commercial Branch Office in Brussels 1979-1984; subdepartment leader at Developed Non-socialist States Interstate Department in the Foreign Trade Ministry 1984-1985; head of the Secretary Department at the Ministry of Foreign Trade 1985-1987; head of the Juridical Department in the Ministry of Commerce", Name: "János", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Kolozsvár (Cluj Napoca)", PlaceOfDeath: "", RelationsBlob: "", Surname: "Martonyi"},
  {Id: 122, DateOfBirth: 991446, DateOfDeath: 0, Description: "<p>In the ministry he was responsible for the inter-bloc relations. He represented his ministry during the inter-ministerial negotiations concerning the EEC and CMEA talks.</p>", DocumentsBlob: "", ElitesBlob: "trader at the Hungarian commercial branch agency in Köln 1969-1974; deputy leader of the Developed Non-socialist States Interstate Department in the Foreign Trade Ministry 1974-1980; deputy minister of the Foreign Trade Ministry 1980-1988", Name: "Tibor", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Budapest", PlaceOfDeath: "", RelationsBlob: "", Surname: "Melega"},
  {Id: 123, DateOfBirth: 984462, DateOfDeath: 1028204, Description: "<p>As the economic secretary of the CC he was responsible for the preparation of proposals dealing with economic policy and foreign economy </p>", DocumentsBlob: "", ElitesBlob: "the economic secretary of the HSWP CC 1974-1987; leader of the Economic Policy Committee 1974-1978", Name: "Károly", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Páka", PlaceOfDeath: "Budapest", RelationsBlob: "", Surname: "Németh"},
  {Id: 124, DateOfBirth: 992353, DateOfDeath: 0, Description: "<p>His research focused on the international integration, the economies of the developed countries, the European integration and Eastern European transformation after 1989/90.</p>", DocumentsBlob: "", ElitesBlob: "lecturer at the Karl Marx University of Economics since 1960; professor of the university since 1982; pro-rector fo the university 1977-1983; head of the World Economy Department of the university 1983-1995", Name: "Tibor", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Jakabszállás", PlaceOfDeath: "", RelationsBlob: "", Surname: "Palánkai"},
  {Id: 125, DateOfBirth: 988292, DateOfDeath: 0, Description: "<p>researcher of the interdependency and conflicts of the world economy, his main publication International Technology Transfer and Economic Development in the Late 20th Century (1984)</p>", DocumentsBlob: "", ElitesBlob: "researcher at the Planning, Prognostical and Economic Policy Center of the United Nations Economic Commission for Europe 1964-1968; professor at the Karl Marx University of Economics 1971-2000; deputy director of the HAS Institute for Research on World Economy 1974-1987; director of the Institute for Research on World Economy 1987-1991", Name: "Mihály", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Budapest", PlaceOfDeath: "", RelationsBlob: "", Surname: "Simai"},
  {Id: 126, DateOfBirth: 990059, DateOfDeath: 0, Description: "<p>As one of the CC secretaries he was responsible for the foreing policy of the state party</p>", DocumentsBlob: "", ElitesBlob: "deputy leader at the Foreign Affairs Department of the HSWP CC 1974-1975; ambassador of Hungary in East-Berlin 1975-1978; ambassador of Hungary in Moscow 1978-1982; head of Foreign Affairs Department of the HSWP CC 1982-1983; the foreign affairs secretary of the HSWP CC 1983–1989 ", Name: "Mátyás", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Püspökladány", PlaceOfDeath: "", RelationsBlob: "", Surname: "Szűrös"},
  {Id: 127, DateOfBirth: 988803, DateOfDeath: 1028431, Description: "<p>He, as foregin minister leaded the negotiations with the EEC</p>", DocumentsBlob: "", ElitesBlob: "headed the secretary of János Kádár 1961-1968; deputy leader of the Foreign Affairs Department of the HSWP CC 1968-1969; head of the Public Relations Office of the Executive Council 1969-1980; editor-in-chief of the party daily 'Népszabadság' 1980-1982; minister of foreign affairs 1983-1989", Name: "Péter", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Budapest", PlaceOfDeath: "Budapest", RelationsBlob: "", Surname: "Várkonyi"},
  {Id: 128, DateOfBirth: 987329, DateOfDeath: 0, Description: "<p></p>", DocumentsBlob: "", ElitesBlob: "deputy minister of foreign trade 1971-1974; ambassador of Hungary in Paris 1974-1979; minister of foreign trade 1979-1987", Name: "Péter", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Gyimesközéplok (Lunca de Jos)", PlaceOfDeath: "", RelationsBlob: "", Surname: "Veress"},
  {Id: 129, DateOfBirth: 979528, DateOfDeath: 1021321, Description: "<p>As one of the older generation orthodox communi...", DocumentsBlob: "", ElitesBlob: "Vice president of the Moon", Name: "Alan", NationalitiesBlob: "Hungarian", PictureId: nil, PlaceOfBirth: "Szeged", PlaceOfDeath: "Budapest", RelationsBlob: "N. Faddeev, secretary general of the CMEA", Surname: "Keys"}
])
Relations::EliteDocument.create!([
  {EliteId: 6, FileId: 9}
])
Relations::FileLanguage.create!([
  {LanguageId: 22, FileId: 9},
  {LanguageId: 22, FileId: 10}
])
Relations::PersonDocument.create!([
  {PersonId: 129, FileId: 9}
])
Relations::PersonNationality.create!([
  {NationalityId: 122, PersonId: 114},
  {NationalityId: 122, PersonId: 115},
  {NationalityId: 122, PersonId: 116},
  {NationalityId: 122, PersonId: 117},
  {NationalityId: 122, PersonId: 118},
  {NationalityId: 122, PersonId: 119},
  {NationalityId: 122, PersonId: 120},
  {NationalityId: 122, PersonId: 121},
  {NationalityId: 122, PersonId: 122},
  {NationalityId: 122, PersonId: 123},
  {NationalityId: 122, PersonId: 124},
  {NationalityId: 122, PersonId: 125},
  {NationalityId: 122, PersonId: 126},
  {NationalityId: 122, PersonId: 127},
  {NationalityId: 122, PersonId: 128},
  {NationalityId: 122, PersonId: 129},
  {NationalityId: 115, PersonId: 129}
])
Relations::PersonPerson.create!([
  {PersonId: 129, OtherPersonId: 114},
  {PersonId: 129, OtherPersonId: 115},
  {PersonId: 129, OtherPersonId: 116}
])
