FGroup.create!([
  {title: "Managers", permissions: "{\"access\":[\"15\",\"24\",\"30\",\"34\",\"42\",\"43\",\"81\",\"82\"]}"},
  {title: "All Users", permissions: "{\"access\":[\"0\"]}"},
  {title: "Steering Committe", permissions: "{\"access\":[\"32\",\"33\",\"34\",\"37\",\"38\",\"40\"]}"}
])
Folder.create!([
  {folder_id: 1, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Clarotti Paolo "},
  {folder_id: 59, master_folder: 0, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"]}", title: "Calendar"},
  {folder_id: 61, master_folder: 0, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Archival Sources"},
  {folder_id: 62, master_folder: 0, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Interviews"},
  {folder_id: 63, master_folder: 0, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Authorisation forms & Guidelines"},
  {folder_id: 64, master_folder: 0, ha_groups: "{\"Manager\":[\"9\"],\"Upload\":[\"11\"]}", title: "Steering Committee"},
  {folder_id: 68, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "1 Administrative structures and staff"},
  {folder_id: 69, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "2 Economic policies"},
  {folder_id: 70, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "3 Social dimension and EU citizenship"},
  {folder_id: 71, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "4 External policies"},
  {folder_id: 78, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Delors Jacques "},
  {folder_id: 81, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Inventories of archival sources stored at the HAEU"},
  {folder_id: 85, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Inventories of archives stored at the HAS of the European Commission"},
  {folder_id: 86, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Directories of the Commission/Organigrammes de la Commission"},
  {folder_id: 87, master_folder: 78, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Document selection for interview"},
  {folder_id: 88, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "General reports/Rapports gÃ©nÃ©raux"},
  {folder_id: 89, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Zepter Bernhard"},
  {folder_id: 90, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "van der Pas Nikolaus "},
  {folder_id: 91, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Upload\":[\"11\"]}", title: "Degimbe Jean "},
  {folder_id: 92, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Santer Jacques "},
  {folder_id: 93, master_folder: 92, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1995"},
  {folder_id: 94, master_folder: 92, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1996"},
  {folder_id: 95, master_folder: 92, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1997"},
  {folder_id: 96, master_folder: 92, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1998"},
  {folder_id: 97, master_folder: 92, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1999"},
  {folder_id: 98, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Legras Guy "},
  {folder_id: 100, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "SchÃ¼ler JÃ¼rgen "},
  {folder_id: 101, master_folder: 71, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The enlargements "},
  {folder_id: 103, master_folder: 101, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The accession of Austria, Sweden and Finland (1995)"},
  {folder_id: 104, master_folder: 103, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The accession of Austria "},
  {folder_id: 107, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Guth Eckhart"},
  {folder_id: 109, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Giraudy Jean-Louis "},
  {folder_id: 121, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Prodi Romano"},
  {folder_id: 122, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Devonic Fay "},
  {folder_id: 123, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Derisbourg Jean-Pierre"},
  {folder_id: 124, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Rencki Georges"},
  {folder_id: 148, master_folder: 71, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Europe and Mediterranean"},
  {folder_id: 151, master_folder: 148, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union"},
  {folder_id: 152, master_folder: 151, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Mediterranan Policy"},
  {folder_id: 153, master_folder: 152, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 154, master_folder: 152, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Angel Vinas Fonds (AV)"},
  {folder_id: 156, master_folder: 152, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "FranÃ§ois Lamoureux Fonds (FL)"},
  {folder_id: 157, master_folder: 152, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Graham J. L. Avery Fonds (GJLA)"},
  {folder_id: 158, master_folder: 152, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Pier Virgilio Dastoli Fonds (PVD)"},
  {folder_id: 159, master_folder: 151, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Turkey"},
  {folder_id: 160, master_folder: 159, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 161, master_folder: 159, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Graham J. L. Avery Fonds (GJLA)"},
  {folder_id: 162, master_folder: 159, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Angel Vinas Fonds (AV)"},
  {folder_id: 163, master_folder: 151, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Egypt"},
  {folder_id: 164, master_folder: 163, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 165, master_folder: 151, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Morocco"},
  {folder_id: 166, master_folder: 165, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 167, master_folder: 151, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jordan"},
  {folder_id: 168, master_folder: 167, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 169, master_folder: 151, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Israel and Palestine"},
  {folder_id: 170, master_folder: 169, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 171, master_folder: 159, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Francois Lamoureux Fonds (FL)"},
  {folder_id: 172, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Fischler Franz"},
  {folder_id: 173, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "FouÃ©rÃ© Erwan"},
  {folder_id: 174, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Pratt Juan"},
  {folder_id: 175, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Servantie Alain "},
  {folder_id: 176, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Zangl Peter"},
  {folder_id: 177, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Mombelli Gerardo"},
  {folder_id: 178, master_folder: 70, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The migrations"},
  {folder_id: 179, master_folder: 178, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 180, master_folder: 179, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Francois Lamoureux Fonds (FL)"},
  {folder_id: 181, master_folder: 179, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 182, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The College of Commissioners"},
  {folder_id: 183, master_folder: 182, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 185, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The Commission Presidency"},
  {folder_id: 186, master_folder: 185, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Romano Prodi"},
  {folder_id: 187, master_folder: 186, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 189, master_folder: 183, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Carlo Ripa di Meana, Commission Delors I"},
  {folder_id: 190, master_folder: 183, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Edith Cresson, Commission Santer"},
  {folder_id: 191, master_folder: 69, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The internal market and the competition policy"},
  {folder_id: 192, master_folder: 71, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The Yugoslav crisis"},
  {folder_id: 193, master_folder: 192, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 194, master_folder: 192, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Francois Lamoureux Fonds (FL)"},
  {folder_id: 195, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Hay Richard"},
  {folder_id: 196, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Keery Neville"},
  {folder_id: 197, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Pappas Spyros "},
  {folder_id: 198, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Busquin Philippe"},
  {folder_id: 199, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Richonnier Michel "},
  {folder_id: 200, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Scrivener Christiane "},
  {folder_id: 201, master_folder: 69, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The industrial policy and the research policy"},
  {folder_id: 202, master_folder: 201, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The industrial policy"},
  {folder_id: 203, master_folder: 148, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "HAS of the European Commission"},
  {folder_id: 204, master_folder: 202, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "HAS of the European Commission"},
  {folder_id: 205, master_folder: 204, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Communications of the European Commission"},
  {folder_id: 206, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1986"},
  {folder_id: 207, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1987"},
  {folder_id: 208, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1988"},
  {folder_id: 209, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1989"},
  {folder_id: 210, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1990"},
  {folder_id: 211, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1991"},
  {folder_id: 212, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1992"},
  {folder_id: 213, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1993"},
  {folder_id: 214, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1994"},
  {folder_id: 215, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1995"},
  {folder_id: 216, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1996"},
  {folder_id: 217, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1997"},
  {folder_id: 218, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1998"},
  {folder_id: 219, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1999"},
  {folder_id: 220, master_folder: 205, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "2000"},
  {folder_id: 221, master_folder: 61, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Bulletins"},
  {folder_id: 222, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Cresson Edith"},
  {folder_id: 223, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Ceri Jones Hywel "},
  {folder_id: 224, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Schinas Margaritis"},
  {folder_id: 225, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Paleokrassas Yannis "},
  {folder_id: 226, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Avery Graham"},
  {folder_id: 227, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: " Davignon Ã‰tienne"},
  {folder_id: 228, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Hall Ronald "},
  {folder_id: 229, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Pirzio-Biroli Corrado"},
  {folder_id: 230, master_folder: 70, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "The Charter of Fundamental Rights of the European Union"},
  {folder_id: 232, master_folder: 230, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 233, master_folder: 232, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\"],\"Upload\":[\"11\"]}", title: "Francois Lamoureux Fonds (FL)"},
  {folder_id: 234, master_folder: 70, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The Regional Policy"},
  {folder_id: 235, master_folder: 234, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 236, master_folder: 235, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Georges Rencki fonds (GR)"},
  {folder_id: 238, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Micossi Stefano"},
  {folder_id: 239, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Perissich Riccardo"},
  {folder_id: 240, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Benda FranÃ§ois"},
  {folder_id: 241, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Roger Christine"},
  {folder_id: 242, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Mayhew Alan"},
  {folder_id: 243, master_folder: 242, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Archival documents"},
  {folder_id: 244, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Erdmenger JÃ¼rgen"},
  {folder_id: 245, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Wall Stephen "},
  {folder_id: 246, master_folder: 204, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The semiconductor industry"},
  {folder_id: 247, master_folder: 204, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The automotive industry"},
  {folder_id: 248, master_folder: 204, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The steel industry"},
  {folder_id: 249, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1986"},
  {folder_id: 250, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1987"},
  {folder_id: 251, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1988"},
  {folder_id: 252, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1989"},
  {folder_id: 253, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1990"},
  {folder_id: 254, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1991"},
  {folder_id: 255, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1992"},
  {folder_id: 256, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1993"},
  {folder_id: 257, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1994"},
  {folder_id: 258, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1995"},
  {folder_id: 259, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1996"},
  {folder_id: 260, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1997"},
  {folder_id: 261, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1998"},
  {folder_id: 262, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1999"},
  {folder_id: 263, master_folder: 247, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "2000"},
  {folder_id: 264, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1986"},
  {folder_id: 265, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1987"},
  {folder_id: 266, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1988"},
  {folder_id: 267, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1989"},
  {folder_id: 268, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1990"},
  {folder_id: 269, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1991"},
  {folder_id: 270, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1992"},
  {folder_id: 271, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1993"},
  {folder_id: 272, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1994"},
  {folder_id: 273, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1995"},
  {folder_id: 274, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1996"},
  {folder_id: 275, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1997"},
  {folder_id: 276, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1998"},
  {folder_id: 277, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1999"},
  {folder_id: 278, master_folder: 246, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "2000"},
  {folder_id: 279, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The cabinets"},
  {folder_id: 280, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The Secretariat-General"},
  {folder_id: 281, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The directorate-generals"},
  {folder_id: 282, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The development of European agencies"},
  {folder_id: 283, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The Legal Service"},
  {folder_id: 284, master_folder: 68, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The Statistical Office"},
  {folder_id: 285, master_folder: 284, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The HAS of the European Commission"},
  {folder_id: 286, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1986"},
  {folder_id: 287, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1987"},
  {folder_id: 288, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1988"},
  {folder_id: 289, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1989"},
  {folder_id: 290, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1990"},
  {folder_id: 291, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1991"},
  {folder_id: 292, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1992"},
  {folder_id: 293, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1993"},
  {folder_id: 294, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1994"},
  {folder_id: 295, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1995"},
  {folder_id: 296, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1996"},
  {folder_id: 297, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1997"},
  {folder_id: 298, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1998"},
  {folder_id: 299, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "1999"},
  {folder_id: 300, master_folder: 285, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "2000"},
  {folder_id: 302, master_folder: 104, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The HAS of the European Commission"},
  {folder_id: 303, master_folder: 71, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The\tdevelopment\t policy"},
  {folder_id: 304, master_folder: 303, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 305, master_folder: 304, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Philip Lowe Fonds (PL)"},
  {folder_id: 306, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Manfredi Marina"},
  {folder_id: 307, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Houtman Anne"},
  {folder_id: 310, master_folder: 202, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 311, master_folder: 310, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Jacques Delors Fonds (JD)"},
  {folder_id: 312, master_folder: 192, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "DORIE"},
  {folder_id: 313, master_folder: 191, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Historical Archives of the European Union, Florence"},
  {folder_id: 314, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Cloos Jim"},
  {folder_id: 315, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "de Silguy Yves-Thibault "},
  {folder_id: 316, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Petite Michel"},
  {folder_id: 317, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Walker David"},
  {folder_id: 318, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Fischer-Dieskau Christian"},
  {folder_id: 319, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "de Schoutheete Philippe"},
  {folder_id: 320, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Leydon Kevin"},
  {folder_id: 321, master_folder: 192, ha_groups: "{\"Manager\":[\"9\"],\"Upload\":[\"10\",\"11\"]}", title: "Courrier du Personnel/Commission en Direct"},
  {folder_id: 322, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Varese Enrica"},
  {folder_id: 323, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "HÃ¤nsch Klaus "},
  {folder_id: 324, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Lamy Pascal"},
  {folder_id: 325, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Macioti Manfredo "},
  {folder_id: 326, master_folder: 310, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Enrico Gibellieri Fonds (EGI)"},
  {folder_id: 329, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Fossati Emiliano "},
  {folder_id: 330, master_folder: 101, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The opening of accession negotiations with the countries of Central and Eastern Europe "},
  {folder_id: 331, master_folder: 330, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The HAS of the European Commission"},
  {folder_id: 332, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"11\"]}", title: "Bourdeau Philippe"},
  {folder_id: 334, master_folder: 62, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "Franchet Yves"},
  {folder_id: 335, master_folder: 101, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The integration of East Germany"},
  {folder_id: 336, master_folder: 335, ha_groups: "{\"Manager\":[\"9\"],\"Access\":[\"10\",\"11\"]}", title: "The HAS of the European Commission"}
])
